package com.application.icafapi.common.util.constant;

public class Email {

    private static String newLine = System.getProperty("line.separator");

    public static final String USER_REGISTRATION_SUBJECT = "Welcome to ICAF 2021";
    public static final String ATTENDEE_REGISTRATION_BODY = "Hello," + newLine + newLine + "Congratulations! Your registration is confirmed!" + newLine +
            "You've successfully completed registration of 'ICAF 2021 Attendee' application." + newLine + newLine + "If you have any questions or concerns, feel free to contact us via," + newLine +
            "icaf2021@gmail.com" + newLine + newLine + "Best Regards," + newLine + "Organizing Committee";

    public static final String RESEARCHER_REGISTRATION_BODY = "Hello," + newLine + newLine + "Thank you for Registering to ICAF 2021" + newLine +
            "You've successfully completed registration of 'ICAF 2021 Researcher' application." + newLine + "Your researcher application is being processed. " +
            "We will review your application and update you about it's status within 48 hours." + newLine + newLine + "If you have any questions or concerns, feel free to contact us via," + newLine +
            "icaf2021@gmail.com" + newLine + newLine + "Best Regards," + newLine + "Organizing Committee";

    public static final String WORKSHOP_REGISTRATION_BODY = "Hello," + newLine + newLine + "Thank you for Registering to ICAF 2021" + newLine +
            "You've successfully completed registration of 'ICAF 2021 Workshop Conductor' application." + newLine + "Your workshop proposal application is being processed. " +
            "We will review your application and update you about it's status within 48 hours." + newLine + newLine + "If you have any questions or concerns, feel free to contact us via," + newLine +
            "icaf2021@gmail.com" + newLine + newLine + "Best Regards," + newLine + "Organizing Committee";

    public static final String COMMITTEE_REGISTRATION_SUBJECT = "Welcome Onboard";

    public static final String REVIEWER_REGISTRATION_BODY = "Hello," + newLine + newLine + "Welcome to ICAF 2021 Organizing Committee" + newLine +
            "This is to inform you that you have assigned as a 'Reviewer' of ICAF 2021" + newLine + "Please login to your account using this email and the below autogenerated password. " +
            "You can change the password once you login to the account." + newLine;
    public static final String EDITOR_REGISTRATION_BODY = "Hello," + newLine + newLine + "Welcome to ICAF 2021 Organizing Committee" + newLine +
            "This is to inform you that you have assigned as an 'Editor' of ICAF 2021" + newLine + "Please login to your account using this email and the below autogenerated password. " +
            "You can change the password once you login to the account." + newLine;
    public static final String ADMIN_REGISTRATION_BODY = "Hello," + newLine + newLine + "Welcome to ICAF 2021 Organizing Committee" + newLine +
            "This is to inform you that you have assigned as an 'Admin' of ICAF 2021" + newLine + "Please login to your account using this email and the below autogenerated password. " +
            "You can change the password once you login to the account." + newLine;

    public static final String COMMITTEE_REGISTRATION_END = newLine + newLine + "If you have any questions or concerns, feel free to contact us via," + newLine +
            "icaf2021@gmail.com" + newLine + newLine + "Best Regards," + newLine + "Organizing Committee";

    private Email() {}

}
